; Общее
memory_limit = 1G
;max_execution_time = 120

; Загрузки
file_uploads = On
upload_max_filesize = 250M
post_max_size = 250M
max_file_uploads = 10

; Это позволит избавиться от многих ненужных вызовов stat() в операционной системе
cgi.fix_pathinfo = 0

; Дата/Время
date.timezone = "UTC"

; Почта
; Отправка почты через Exim4
[mail function]
sendmail_path = /usr/sbin/exim -t

mail.add_x_header = On
mail.log = syslog

; Для работы VIPS
;extension=ffi
[ffi]
; FFI API restriction. Possible values:
; "preload" - enabled in CLI scripts and preloaded files (default)
; "false"   - always disabled
; "true"    - always enabled
ffi.enable = true

; Для корректной работы VIPS
; https://github.com/libvips/php-vips/pull/237
zend.max_allowed_stack_size = -1
