####
# Reverse proxy for NGINX + Docker installation
####

## HTTP → HTTPS
server {
	listen 80;
	listen [::]:80;
	server_name webscore.maximals.ru *.webscore.maximals.ru;
	server_tokens off; ## Don’t show the nginx version number
	return 301 https://webscore.maximals.ru$request_uri;

	access_log off;
	error_log  off;
}

## HTTPS: *.webscore.maximals.ru → webscore.maximals.ru
server {
	server_name *.webscore.maximals.ru;
	return 301 https://webscore.maximals.ru$request_uri;
	listen 443 ssl;
	listen [::]:443 ssl;
	ssl_certificate      /etc/letsencrypt/live/webscore.maximals.ru/fullchain.pem;
	ssl_certificate_key  /etc/letsencrypt/live/webscore.maximals.ru/privkey.pem;
}

## HTTPS host
server {
	listen 443 ssl;
	listen [::]:443 ssl;

	server_name webscore.maximals.ru;
	server_tokens off; ## Don’t show the nginx version number

	## Strong SSL Security
	## https://raymii.org/s/tutorials/Strong_SSL_Security_On_nginx.html & https://cipherli.st/
	ssl_certificate      /etc/letsencrypt/live/webscore.maximals.ru/fullchain.pem;
	ssl_certificate_key  /etc/letsencrypt/live/webscore.maximals.ru/privkey.pem;

	## Real IP Module Config
	## http://nginx.org/en/docs/http/ngx_http_realip_module.html
	#real_ip_header X-Real-IP; ## X-Real-IP or X-Forwarded-For or proxy_protocol
	#real_ip_recursive on;

	## If you have a trusted IP address, uncomment it and set it
	# set_real_ip_from YOUR_TRUSTED_ADDRESS; ## Replace this with something like 192.168.1.0/24
	#set_real_ip_from 0.0.0.0/0;
	#real_ip_header CF-Connecting-IP;
	#include /etc/nginx/cloudflare-real-ip.conf;

	# Логи
	access_log /var/log/nginx/webscore.maximals.ru-access.log;
	error_log  /var/log/nginx/webscore.maximals.ru-error.log;

	location / {
		client_max_body_size  10m;

		proxy_read_timeout    15s;
		proxy_send_timeout    15s;
		send_timeout          10s;
		resolver_timeout      15s;
		client_body_timeout   15s;

		proxy_set_header    Host                $http_host;
		proxy_set_header    X-Forwarded-Proto   $scheme;
		proxy_set_header    X-Forwarded-For     $remote_addr;
		proxy_set_header    X-Real-IP           $remote_addr;
		proxy_set_header    X-Forwarded-Ssl     on;

		proxy_set_header    Upgrade             $http_upgrade;
		proxy_redirect      off;

		#sub_filter_types text/html;
		#sub_filter '</head>' '<link rel="stylesheet" media="all" href="/css/sijeko.css" />\n</head>';
		#sub_filter_once on;

		proxy_pass        http://127.0.0.1:8001;

		add_header Strict-Transport-Security "max-age=31536000";
	}
}
